### ISSUE TITLE
[BUG] The given role or permission should use guard `sanctum` instead of `web`. 

### ISSUE THREAD

**Issue by neo909** [TiagoSilvaPereira/vemto-issues#112]
**Describe the bug**
When creating a new role under access management, the following error occurs.

Spatie\Permission\Exceptions\GuardDoesNotMatch
_**The given role or permission should use guard `sanctum` instead of `web`.**_
http://demo.test/roles 

If you refresh the role is created, but you can't see the permissions.  One work around found [TEMP solution for local dev enviroment] was to create the role with the error, manually change the auth type value in the roles table to the affected row, then it continues to work as expected. 

**To Reproduce**
1. Go to `Go to Roles under access management`
2. Click on 'Create new role'
3. Save the new role 

**Expected behavior**
Create role and save with correct guard type

**Screenshots**
![image](https://user-images.githubusercontent.com/77210693/114087232-dc04e700-9870-11eb-8a0b-53f6323e6432.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by jvallef** [comment]
Well, I came late, you did all the work @neo909 thought :-)

Pasting comment I left in Discord...

Generated yesterday a testing Crud with default settings and two tables Users, as default, and Blogs, with title, body, image and belonging to User.

To continue exploring options created a new role bossito, with permissions over blogs and also to list and view users. Then...

Error creating a new role. At http://vemto.test/roles

Error displayed:
Spatie\Permission\Exceptions\GuardDoesNotMatch
The given role or permission should use guard sanctum instead of web

Spatie\Permission\Exceptions\GuardDoesNotMatch::create
vendor/spatie/laravel-permission/src/Exceptions/GuardDoesNotMatch.php:12

**Comment by TiagoSilvaPereira** [comment]
Hi @jvallef @neo909 thank you for reporting, I'll fix this bug ASAP.

Cheers

**Comment by TiagoSilvaPereira** [comment]
Fixed on 0.8.3
