### ISSUE TITLE
[BUG ??! ] The paginator "'resources/views/vendor/livewire/tailwind.blade.php" doesn't work in Vemto templates

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#118]
I work in Jetstream LiveWire, in a project generated in Vemto
I need to individually customize the pagination view for different site designs.
As it is written in the documentation, I perform " php artisan livewire:publish --pagination”
And I make a second paginator at the beginning of the template \app\users\index.blade.php
{!! $users->render('vendor.livewire.tailwind')!!}
……….
And I leave the paginator at the bottom of the table unchanged
{!! $users->render() !!}

The paginators are displayed correctly, but the upper / new paginator does not respond to mouse clicks, and the lower (original) one works fine.

**Did I do something wrong ? or is it a bug in the vemto/jetstream templates ?**
And why does the Vemto template use $users - >render(), while the documentation says
$users->links() ?

**If possible, please send us an example line of code on how to use the 'resources/views/vendor/livewire/tailwind' paginator in the Vemto template.blade.php. (for example, for a template \app\users\index.blade.php)**

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 ,

It is due to the way Livewire works... The index.blade.php page is not a Livewire component, so the correct way of customizing the pagination for this page is by publishing the default laravel pagination files, instead of the Livewire pagination.

About the render() or links() methods, they are only syntactic sugar. You can use both, they have exactly the same behavior.

Sincerely,
Tiago
