### ISSUE TITLE
[BUG] Has started to play with master detail and has received an error

### ISSUE THREAD

**Issue by StasKoun2** [TiagoSilvaPereira/vemto-issues#164]
I was experimenting with different options and suddenly got an error

![nnn_9000001 Has started to play with master detail and has received an error](https://user-images.githubusercontent.com/80303996/120816120-aa5f8200-c57a-11eb-82c1-32dce7bfb130.jpg)
![nnn_9000002](https://user-images.githubusercontent.com/80303996/120816156-b2b7bd00-c57a-11eb-91f8-5fa79afe055d.jpg)
![nnn_9000003](https://user-images.githubusercontent.com/80303996/120816176-b8150780-c57a-11eb-81e2-20ff52f4a217.jpg)
![nnn_9000004](https://user-images.githubusercontent.com/80303996/120816204-be0ae880-c57a-11eb-8125-a589cbe1024c.jpg)

**Comment by TiagoSilvaPereira** [comment]
Hi @StasKoun2 the problem is happening due to the model names (A, B, C)... Vemto is generating the table names as: as, bs, cs, but Laravel is trying to use the tables: a_s, b_s, c_s... I recommend these ways to fix it:

- Change your models' names to use words instead of single characters (e.g. Post, Comment, Order, etc), so Vemto will generate the correct table names
- Or, change your generated Models to point to the tables Vemto generated:

```php
class A extends Model {
    protected $table = 'as';
}
```

Except for extraordinary scenarios, I don't recommend using single characters to name your models. Please, try to always use complete words to do it.

Best regards,
Tiago
