### ISSUE TITLE
When Generating Code with tailwind css breeze

### ISSUE THREAD

**Issue by bahast7** [TiagoSilvaPereira/vemto-issues#203]
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
When Generating Code with tailwind css breeze it will make an composer error that is not true

**To Reproduce**
1. Go to Project Setting
2. Click on Views
3. Select CSS Framework Tailwind CSS
4. Select Breeze as UI Template

**Expected behavior**
 it will make an composer error that is not true

**Screenshots**
 
![Screenshot (3)](https://user-images.githubusercontent.com/56611529/126707279-fddf2cae-8acf-486b-8e4d-f1d5f1b51b4d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 90.0.2

**Comment by TiagoSilvaPereira** [comment]
Hi @bahast7 it is a composer bug, generally due to using an incorrect composer version, incompatible with your PHP version. Please check these links:

https://laracasts.com/discuss/channels/laravel/fclose-argument-1-stream-must-be-of-type-resource-bool-given

https://stackoverflow.com/questions/66109427/fclose-argument-1-stream-must-be-of-type-resource-bool-given
