### ISSUE TITLE
I just got this error trying to add a new CRUD

### ISSUE THREAD

**Issue by precamp-io** [TiagoSilvaPereira/vemto-issues#294]
```
TypeError: Cannot read property 'type' of undefined
    at Function.getCorrectInputFromFieldAndCrud (app://./js/chunk-common.3cbeda44.js:1:66174)
    at Proxy.addInputToCrud (app://./js/chunk-common.3cbeda44.js:1:26434)
    at app://./js/chunk-common.3cbeda44.js:1:35217
    at Array.forEach (<anonymous>)
    at Proxy.addInputsFromModel (app://./js/chunk-common.3cbeda44.js:1:35204)
    at Function.fromModel (app://./js/chunk-common.3cbeda44.js:1:34541)
    at o.create (app://./js/project_apps.2f6b5514.js:1:12235)
    at app://./js/project_apps.2f6b5514.js:1:12207
```

---

vemto 1.1.2
Electron 8.5.5
win32 10.0.22000
Locale: en-US

**Comment by TiagoSilvaPereira** [comment]
Hi @precamp-io could you please share the project .vemto file and what CRUD you are trying to add, so I can reproduce it here?

**Comment by precamp-io** [comment]
I am still new to the program can you tell me where to go to get this for you?On 5 Apr 2022 13:21, "Tiago S. P. Rodrigues" ***@***.***> wrote:
Hi @precamp-io could you please share the project .vemto file and what CRUD you are trying to add, so I can reproduce it here?

**Comment by precamp-io** [comment]
Glitches happen, all good thanks trying anywaysOn 5 Apr 2022 13:21, "Tiago S. P. Rodrigues" ***@***.***> wrote:
Hi @precamp-io could you please share the project .vemto file and what CRUD you are trying to add, so I can reproduce it here?

**Comment by TiagoSilvaPereira** [comment]
Hi  @precamp-io you can export it from the Home Page

**Comment by TiagoSilvaPereira** [comment]
Hi @TiagoSilvaPereira I can't access the file here... could you please send a link with the file?

**Comment by precamp-io** [comment]
Yes sure https://www.precamp.io/uploads/precamp_vemto.zip

**Comment by TiagoSilvaPereira** [comment]
Hi @precamp-io I found that the problem is happening due to some problems with your Schema modeling (for future versions I'll add a way to avoid it happening). 

But let me give you some tips so you can take your project running:

1 - You are adding Foreign Keys with incorrect types. If a foreign key references a **bigIncrements**, it needs to be an **Unsigned bigInteger**.  **I recommend using relationships instead of creating the foreign keys manually, and let Vemto take care of it for you** (https://vemto.app/docs/1.x/relationships). By default, Laravel automatically creates foreign keys and pivot tables when you add relationships to the models.
![image](https://user-images.githubusercontent.com/11933789/162211273-ad1f0db6-3c36-42c6-b24e-581cdc688b23.png)

2 - You are not following [Laravel standards/conventions](https://webdevetc.com/blog/laravel-naming-conventions/) for **pivot tables, foreign keys, etc**. Again, I recommend using BelongsToMany relationships and letting Vemto create the pivot tables correctly (**or maybe you need a model with a hasMany relationship?**):

![image](https://user-images.githubusercontent.com/11933789/162212192-23a67ba3-465c-45e7-9e1a-c9175f4ce49b.png)

3 - If you are just starting with Laravel, and if you can, I strongly recommend taking a Laravel course before using Vemto. Seems some concepts are not clear yet, like inverse foreign keys types, table naming conventions, indexes naming conventions, etc. I can recommend this free Laravel course, it is very good: https://laracasts.com/series/laravel-8-from-scratch

As Vemto is a Laravel tool, it is easier to use it when you understand Laravel better and follow its conventions.

My best regards

**Comment by precamp-io** [comment]
Thank you really appreciate you looking into this for me.
