### ISSUE TITLE
[BUG] Order of Migration files created

### ISSUE THREAD

**Issue by MarkD95** [TiagoSilvaPereira/vemto-issues#30]
**Describe the bug**
When designing a database schema using the schema builder and exporting said design, the exported migration files are out of order in the sense that foreign key constraints on some of the tables attempting to be migrated are not valid due to the foreign table not existing yet (yet to be migrated).
**To Reproduce**
1. Design a database schema with a few relationships between the tables
2. Generate migration files
3. Attempt to run `php artisan migrate`

**Expected behavior**
Expect migrations to be migrated successfully without having to rename the migration files timestamps after inspecting which tables need to be created before others.

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.17

**Additional context**
Also just a side note, was noticing significant performance issues and hanging when a large schema is being designed (44 Tables)

**Comment by TiagoSilvaPereira** [comment]
Hi @MarkD95 thank you for reporting. Could you please send me a screenshot of your Schema so I can reproduce the issue? By default, Vemto tries to order the migrations based on foreign keys, so I would need to check the Schema to understand what is happening. Have a nice day!

**Comment by buckhornmktg** [comment]
I'm having this issue too. Maybe the solution is to put the foreign keys in a separate migration files that run after all the tables are created.

**Comment by TiagoSilvaPereira** [comment]
@buckhornmktg could you please send a screenshot of your Schema (you can send it to the email contact@vemto.app if you prefer)... Vemto by default tries to order the migrations based on the foreign, but I probably missed some scenario in the algorithm that does this sorting. Thanks, have a nice day

**Comment by buckhornmktg** [comment]
I'll send a screenshot shortly, but trying to keep the FKs in sync is not a great approach. Here's what you should be doing...

Build all your migrations w/o the FK. 

**create_notes_table.php**

        Schema::create('notes', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('user_id')->index('notes_user_id_foreign');
            $table->string('status')->default('private');
            $table->string('title')->nullable();
            $table->text('note')->nullable();
            $table->timestamps();
        });

Then build a second set of migrations for the FKs. This way you never run into this problem, because your first set of migrations will build all the tables. Then when the second set of migrations run, there will be no issues with missing tables/fields. 

**add_foriegn_key_to_notes_table.php**

        Schema::table('notes', function (Blueprint $table) {
            $table->foreign('user_id')->references('id')->on('users')->onUpdate('CASCADE')->onDelete('RESTRICT');
        });

**Comment by TiagoSilvaPereira** [comment]
Hi @MarkD95 and @buckhornmktg sorry for the late, this week I fixed a lot of issues and made a lot of improvements with Vemto.

@buckhornmktg Thank you very much for your suggestion, I just implemented it and it worked perfectly (The problem with the migrations is that I was generating wrong migration names, eg: instead of date_000015_create..., I was generating date_150000_create... as @MarkD95 correctly pointed, so it was ordering the migrations incorrectly. But I decided to change completely to your method, as it is much better and cover a lot of scenarios like circular relationships, etc)

@MarkD95 I made huge performance improvements too, Vemto is now at least 5x faster than before. I hope it helps you with the performance problems that you had.

Have a wonderful day.

Best Regards,
Tiago
