### ISSUE TITLE
Laravel UI with Mix causes Vite error

### ISSUE THREAD

**Issue by Benoit1980** [TiagoSilvaPereira/vemto-issues#348]
Vemto 1.1.8

I ran 1 new project set with:
Laravel UI, **Vite**, Tailwind CSS. When going to the login page, the error shown is:
"Unable to locate file in Vite manifest: resources/css/app.css."

I ran 1 new project set with:
Laravel UI, **Mix**, Tailwind CSS. When going to the login page, the error shown is:
"Unable to locate file in Vite manifest: resources/css/app.css."

Both a Vite error in the projects.

**Comment by Benoit1980** [comment]
I checked further tonight, having huge problems generating anything with Laravel UI.
I restarted the pc, deleted the projects and tried to recreate them, now they are stuck on "npm run dev" for over 20 minutes.

Not sure what is happening as I am not seeing any logs.

**Comment by TiagoSilvaPereira** [comment]
Hello, new projects should always keep the configuration as Vite... we put the option to switch to Mix to maintain compatibility with old projects (and soon this option will be discontinued). This is because Laravel's default boilerplate no longer has the default Mix installation and we don't intend to keep an outdated boilerplate aside.

Therefore, for new projects, the correct thing is to keep the configuration as Vite (note that npm run dev is stuck because in fact the Laravel repository already comes with Vite, but the npm run dev command is now equivalent to the old npm run watch , so it gets stuck and doesn't continue the generation). And so the configuration must be Vite, for Vemto to run the correct command: npm run build.

**Comment by Benoit1980** [comment]
Laravel continuous upgrades are really a nightmare, I cannot understand why they do not keep things stable without any changes for a good 2 or 3 years at the time. I will try with VITE tonight to see if it works. I never used VITE, so this is still new to me. Thanks
