### ISSUE TITLE
Look I have serious issue with vemto its not reliable while making update and correction in that uml let me explain

### ISSUE THREAD

**Issue by patrickzuili** [TiagoSilvaPereira/vemto-issues#391]
getting continuously this error
 (PDOException(code: HY000): SQLSTATE[HY000]: General error: 3780 Referencing column 'claim_number' and referenced column 'id' in foreign key constraint 'claims_claim_number_foreign' are incompatible. at /Users/patrickzuili/Documents/TSI/tsi_insurance/vendor/laravel/framework/src/Illuminate/Database/Connection.php:544)

The only issue is that I dropped that table and crud accordingly but still while doing generating and running old bugged code is still showing while running  preventing to test anything, normally when you drop a table and remove the crud why in hell this code showing in a migration ?

2014_10_12_000000_create_users_table ................................................................................................ 26ms DONE
  2014_10_12_100000_create_password_resets_table ...................................................................................... 12ms DONE
  2019_08_19_000000_create_failed_jobs_table .......................................................................................... 30ms DONE
  2019_12_14_000001_create_personal_access_tokens_table ............................................................................... 22ms DONE
  2022_09_14_000001_create_adjusters_table ............................................................................................ 39ms DONE

WHY is this still showing up on a migration when I removed the table ? and CRUD ?

  **2022_09_14_000002_create_claimcorrections_table ..................................................................................... 38ms DONE
  2022_09_14_000003_create_claim_reviews_table ........................................................................................ 21ms DONE
  2022_09_14_000004_create_claims_table ............................................................................................... 45ms DONE
  2022_09_14_000005_create_claimsstatuses_table ....................................................................................... 32ms DONE**

  2022_09_14_000006_create_invites_table .............................................................................................. 12ms DONE
  2022_09_14_009001_add_foreigns_to_adjusters_table ................................................................................... 42ms DONE
**
  2022_09_14_009002_add_foreigns_to_claims_table ....................................................................................... 1ms FAIL**

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 3780 Referencing column 'claim_number' and referenced column 'id' in foreign key constraint 'claims_claim_number_foreign' are incompatible. (SQL: alter table `claims` add constraint `claims_claim_number_foreign` foreign key (`claim_number`) references `claimcorrections` (`id`) on delete CASCADE on update CASCADE)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:759
    755▕         // If an exception occurs when attempting to run a query, we'll format the error
    756▕         // message to include the bindings with SQL, which will make this exception a
    757▕         // lot more helpful to the developer instead of just the database's errors.
    758▕         catch (Exception $e) {
  ➜ 759▕             throw new QueryException(
    760▕                 $query, $this->prepareBindings($bindings), $e
    761▕             );
    762▕         }
    763▕     }

      +9 vendor frames 
  10  database/migrations/2022_09_14_009002_add_foreigns_to_claims_table.php:22
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +36 vendor frames 
  47  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Cons

**Comment by TiagoSilvaPereira** [comment]
@patrickzuili Suppose you removed the table and Vemto didn't remove the migrations (which is strange behavior, maybe your project migrations settings are incorrect, you can check them inside the Project settings). **In that case, you could delete them manually from your project folder, and the errors will disappear**. Generally, Vemto deletes migrations when you delete a model/table and run the code generator again, so I believe something unusual has happened in your case. The only thing I can think of at the moment is naming issues, which can be fixed in migrations settings.

By observing the errors, I suppose you are new to Laravel (notice these errors are not from Vemto but from Laravel).

I recommend you learn Laravel before using Vemto, as Vemto is a Laravel tool. It is essential to know how Laravel migrations work and understand what Vemto is capable of. I recommend this excellent free Laravel course: https://laracasts.com/series/laravel-8-from-scratch

Still, I recommend letting Vemto generate the FKs for you. So you can follow these steps:

1 - Create your models without FKs (avoid creating tables, create them only when necessary, as you probably want models, not tables, for building your apps)
2 - Add relationships to your models
3 - Vemto will automatically generate the correct FKs, with the correct typings, based on your relationships

Best regards
