### ISSUE TITLE
Vemto Project not detected or disappeared after minor modifications

### ISSUE THREAD

**Issue by Apechi** [TiagoSilvaPereira/vemto-issues#427]
Today, when I opened Vemto, I found that the project I was working on and using suddenly disappeared, and I'm not sure why. The project is still present in the designated folder as set in Vemto's settings, so I assume it is not being detected by Vemto. I made a few changes to the project earlier, but they were minor modifications to the controller and the addition of a datatable.

#Steps Taken:
I have already researched the previous issues in this repository, but it seems that no one has encountered the same problem as mine. I read that Vemto stores its data in Appdata/Roaming/vemto/storage. Upon checking the JSON folder, I can see remnants of my project, such as entities, cruds, and comments, but the project contents are missing from the projects folder. However, the JSON file for the project is still present.

I have attached some photos to provide additional context regarding the error I'm experiencing.

![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/106357977/4fe510a4-13d5-4b64-832d-379c4a21a6d8)
![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/106357977/37f9cd35-1e99-44ef-92c0-435e04bcdcd9)
![image](https://github.com/TiagoSilvaPereira/vemto-issues/assets/106357977/18615367-735d-4682-9557-5c216f18c1f8)

Thank you in advance.

vemto ver 1.2.2.0

Edit: Replacement of the photo as I mistakenly took a photo in the folder that I had already backed up, and correction of the text in the photo

**Comment by TiagoSilvaPereira** [comment]
@Apechi Hello... it looks like something has corrupted your item_4.json file, which is the file that holds the project. This problem has never occurred before in the almost 3 years of the Vemto's life, so I believe it could be something very specific, perhaps a momentary write failure in the Vemto itself, or in the computer, or in the operating system. I believe you can try the Windows File History feature to recover the file:

[https://7datarecovery.com/blog/restoring-previous-versions](https://7datarecovery.com/blog/restoring-previous-versions)

You can also make backups by downloading the .vemto file from the Vemto splash screen if you would like an added security feature.

In Vemto 2, we have a different approach in which the project files will be inside the same folder and can be sent to the repository so that it is always possible to have a backup so that this problem never occurs.

I hope it helps you

**Comment by Apechi** [comment]
Hi,

Thank you for your response and for providing a solution to this issue.

So, just to clarify, this has never happened before, correct? It's possible that the file became corrupt, and I had the same thought.

I tried the methods mentioned in the article you shared and explored other options for data recovery, data restoration, and data corruption. Unfortunately, none of these methods were successful in recovering the lost content of the JSON project file.

I will take this as a lesson to always be cautious and prepared by backing up the .vemto files in case this situation arises again. I appreciate the Vemto team for considering this matter and working towards changing the project folder system for Vemto 2 in the future.

Thank you once again for your assistance.

**Comment by TiagoSilvaPereira** [comment]
My pleasure @Apechi , I'm sorry you weren't able to recover the file. This got me thinking, and in addition to the folder being inside the project, I'm going to modify Vemto 2 to always write a backup copy of the data. That way, if there is a problem, the backup can be restored.
