### ISSUE TITLE
Switching the project from Vite to Mix causes code generation to fail.

### ISSUE THREAD

**Issue by TechBright-Services** [TiagoSilvaPereira/vemto-issues#433]
When switching the project from Vite to Mix causes code generation to fail.

To reproduce create a Vite based project, then generate the code, then switch the setting from Vite to Mix and generate code again. You will find that the code generation just hangs on the "npm run dev" command. I believe this is because when switching it leaves the Vite package and configuration in place rather than removing it.

I am guessing the expected behaviour would be to remove Vite entirely and replace with Mix. Unless this is by design?

Windows 10, Vemteo 1.3.3

**Comment by TiagoSilvaPereira** [comment]
@TechBright-Services, it is not recommended to change Vite to Mix... we only added this option to support old projects during the transition phase. I haven't removed this option because soon after, I started the development of Vemto 2, so this option ended up staying. In Vemto 2, we won't have this kind of problem because it won't be responsible for handling the stack you use, only for generating and editing the relevant application code.
