### ISSUE TITLE
[BUG] errno: 150 "Foreign key constraint is incorrectly formed" 

### ISSUE THREAD

**Issue by katielgc** [TiagoSilvaPereira/vemto-issues#73]
**Describe the bug**
When running php artisan migrate:fresh to generate the databases I get this error : 

 SQLSTATE[HY000]: General error: 1005 Can't create table `db`.`packages` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `packages` add constraint `packages_company_id_foreign` foreign key (`company_id`) references `companies` (`id`))

I do have a lot of relations on my project and I do think I could just be getting confused by hasMany and BelongsToMany relationships so apologies if this is not a bug. 

I am also getting another issue where the role controller is being generated twice and not sure how that keeps happening too.

![image](https://user-images.githubusercontent.com/32128119/106924261-cfe09a00-6706-11eb-9e32-09ed469851a0.png)

![image](https://user-images.githubusercontent.com/32128119/106924324-dec74c80-6706-11eb-8a52-47299263ceb4.png)

 

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser - N/A
 - Version 0.72 Vemto

Let me know if it would help to send a google link to the project. 

Thanks in advance

**Comment by TiagoSilvaPereira** [comment]
Hi @katielgc thank you for your contact and interest in Vemto. About the related issues:

1 - The problem is that the companies **id** was changed to **unsignedBigInteger**... For Laravel, the correct is using the **bigIncrements** type, as it is a primary key (**unsignedBigInteger** is generally used for the inverse foreign key). I recommend always letting Vemto take care of the primary keys and foreign keys to avoid this problem.

2 - As you created a model called Roles, please uncheck the Permissions module when generating the code, as the package Spatie/Laravel-Permissions has a model called Roles too. 

Have a nice day. Cheers

**Comment by katielgc** [comment]
@TiagoSilvaPereira thank you for this :) I haven't changed the id in companies this was what Vemto created! This was on an older version would you suggest trying again in the new one? 

Thanks again!

**Comment by TiagoSilvaPereira** [comment]
Hi @katielgc yes, please change to the latest Vemto version... for this specific problem, you can just change the PK type to bigIncrements on the companies table
